const SOCIALS = {
    LINKEDIN: 'LINKEDIN',
    GITHUB: 'GITHUB',
    FACEBOOK: 'FACEBOOK',
    TELEGRAM: 'TELEGRAM',
    INSTAGRAM: 'INSTAGRAM',
};

export const {LINKEDIN, GITHUB, FACEBOOK, TELEGRAM, INSTAGRAM} = SOCIALS;