const SOCIALS = {
    LINKEDIN: 'LINKEDIN',
    GITHUB: 'GITHUB',
    FACEBOOK: 'FACEBOOK',
    TELEGRAM: 'TELEGRAM',
    INSTAGRAM: 'INSTAGRAM',
    YOUTUBE: 'YOUTUBE',
};

export const { LINKEDIN, GITHUB, FACEBOOK, TELEGRAM, INSTAGRAM, YOUTUBE } = SOCIALS;